import Foundation
import CryptoKit
import Capacitor

// Signed OTA content channel (Phase 1B of docs/app-remediation-plan.md).
//
// The app ships a bundled snapshot of the site. This updater lets a crisis-number
// fix merged to main reach installed apps WITHOUT an App Store release — and lets
// nothing else in. The chain of custody:
//
//   1. The site build emits /ota/manifest.json (sha256 of every content file)
//      and manifest.sig, an ed25519 signature over the manifest's exact bytes,
//      made with a private key held as a deploy secret. (site/tools/gen-ota-manifest.mjs)
//   2. On launch the app fetches both, and verifies the signature against the
//      PUBLIC key compiled into this file. An unsigned or tampered manifest is
//      refused outright — the app then simply keeps serving what it has.
//   3. Files whose hash differs from the active content are downloaded from the
//      manifest's BLOB STORE (see below), each verified against its sha256 FROM
//      THE SIGNED MANIFEST before being kept.
//   4. A complete new content root is STAGED next to the active one (unchanged
//      files are hard-linked, so disk cost is only the delta), then activated
//      atomically by a pointer file.
//   5. Activation happens on the NEXT launch — never mid-session, so a page is
//      never yanked out from under someone reading it. WikiBridgeViewController
//      asks activeContentRoot() for the serving root before the webview loads.
//   6. Rollback: the previous root is kept. If the current root fails its
//      launch-time validation, the app falls back previous → bundle. The bundle
//      is never deleted — there is always a last-known-good.
//
// A NEW BINARY always wins: if the bundle is newer than the OTA content (an App
// Store update shipped), all OTA state is discarded. This mirrors Capacitor's own
// isNewBinary handling and prevents an old OTA root from shadowing a fresh bundle.
//
// WHY BLOBS AND NOT SITE URLS (schema 2, 2026-07-25). This client used to fetch
// each changed file from its real site URL. Through Cloudflare that can never
// work: the edge rewrites html responses (Email Obfuscation turns `mailto:` into
// `/cdn-cgi/l/email-protection`, Bot Management injects the `__CF$cv$params`
// script), so the bytes arriving here never match the sha256 the signed manifest
// vouches for. Every update aborted on its first html file — and a crisis-number
// fix IS an html change, so the channel had never once delivered an update on a
// real device. The publish side now republishes every file under the hash of its
// own bytes at /ota/blobs/<first2>/<sha256>, pinned to `application/octet-stream`
// by site/public/_headers, which keeps it outside every html transform. Integrity
// is unchanged: the sha256 still comes from the signed manifest, so a swapped or
// corrupted blob is still refused.
//
// The corollary, for whoever tests this next: `wrangler pages dev` serves origin
// bytes with none of the edge features on, so it CANNOT reproduce this class of
// failure. That is why the 2026-07-23 E2E test passed on a channel that was dead.
// Test against the real origin, or at minimum re-read the notes in app/README.md.

final class OTAUpdater {
    static let shared = OTAUpdater()

    // Raw 32-byte ed25519 public key, base64. Counterpart of the OTA_SIGNING_KEY
    // deploy secret; generated by app/tools/ota-keygen.mjs. Rotating the key means
    // shipping a binary update with the new value here.
    private static let publicKeyB64 = "FJ3cdXKy8s/zSH83UtiEkF/Us5UYyiLN0rGhqngepGw="

    private enum Keys {
        static let lastCheck = "OTALastCheck"
        static let lastOutcome = "OTALastOutcome"
        static let lastDetail = "OTALastDetail"
        static let pendingVersion = "OTAPendingVersion"
        static let baseURLOverride = "OTABaseURL"
    }

    // Origin for the manifest AND content blobs. Debug/E2E builds may override via
    // `-OTABaseURL http://localhost:8788` launch arguments (UserDefaults).
    private var baseURL: URL {
        if let s = UserDefaults.standard.string(forKey: Keys.baseURLOverride), let u = URL(string: s) {
            return u
        }
        return URL(string: "https://disabilitywiki.org")!
    }

    // Refuse absurd deltas — a corrupt-but-signed manifest must not fill the disk.
    private let maxDeltaBytes = 300 * 1024 * 1024

    private let fm = FileManager.default
    private let defaults = UserDefaults.standard

    private var contentDir: URL {
        let lib = fm.urls(for: .libraryDirectory, in: .userDomainMask)[0]
        return lib.appendingPathComponent("NoCloud/dw-content", isDirectory: true)
    }
    private var versionsDir: URL { contentDir.appendingPathComponent("versions", isDirectory: true) }
    private var currentPointer: URL { contentDir.appendingPathComponent("current") }
    private var previousPointer: URL { contentDir.appendingPathComponent("previous") }

    private var bundleRoot: URL? {
        Bundle.main.url(forResource: "public", withExtension: nil)
    }

    // The version handed to the webview THIS launch, captured on the first call to
    // activeContentRoot() (WikiBridgeViewController.instanceDescriptor, before the
    // webview loads). Staging later in the session moves the `current` pointer but
    // not what is on screen, so this is what "restart to apply" is measured against.
    private var servingVersion: String?
    private var didCaptureServingVersion = false

    // Launch and the status sheet's "Check now" both land here. They shared one
    // staging directory with nothing serialising them, so a reader tapping "check
    // now" mid-download could have the second run wipe the first's partial work —
    // and because launch validation is a four-file spot check, the resulting
    // incomplete root could pass and activate. See OTASingleFlight.
    private let flight = OTASingleFlight()

    // MARK: - Serving root (called before the webview loads)

    /// The content root the webview should serve, or nil to use the app bundle.
    /// Cheap by design: pointer chase + structural validation + 3 hash spot-checks.
    func activeContentRoot() -> URL? {
        // New binary wins: bundle newer than OTA content → discard OTA state.
        if let bundleBuilt = builtAt(inRoot: bundleRoot),
           let otaRoot = pointedRoot(currentPointer),
           let otaBuilt = builtAt(inRoot: otaRoot),
           bundleBuilt > otaBuilt {
            try? fm.removeItem(at: contentDir)
            defaults.removeObject(forKey: Keys.pendingVersion)
            return captureServing(nil)
        }
        if let root = pointedRoot(currentPointer), validate(root: root) {
            return captureServing(root)
        }
        // Current is broken: roll back. Promote previous to current so the bad
        // root is never retried, and let staging start over from good state.
        if let prev = pointedRoot(previousPointer), validate(root: prev) {
            try? fm.removeItem(at: currentPointer)
            try? fm.moveItem(at: previousPointer, to: currentPointer)
            CAPLog.print("⚡️  OTA: current content failed validation — rolled back to previous")
            return captureServing(prev)
        }
        if fm.fileExists(atPath: contentDir.path) {
            try? fm.removeItem(at: contentDir)
            defaults.removeObject(forKey: Keys.pendingVersion)
            CAPLog.print("⚡️  OTA: content state invalid — reverted to app bundle")
        }
        return captureServing(nil)
    }

    private func captureServing(_ root: URL?) -> URL? {
        if !didCaptureServingVersion {
            didCaptureServingVersion = true
            servingVersion = root?.lastPathComponent
            // A staged update that is now the serving root has been applied.
            if let pending = defaults.string(forKey: Keys.pendingVersion), pending == servingVersion {
                defaults.removeObject(forKey: Keys.pendingVersion)
            }
        }
        return root
    }

    /// True when a verified update is staged but the running webview is still on
    /// the older root — i.e. reopening the app is all that's left to apply it.
    private var updateAwaitingRestart: Bool {
        guard let pending = defaults.string(forKey: Keys.pendingVersion) else { return false }
        return pending != servingVersion
    }

    private func pointedRoot(_ pointer: URL) -> URL? {
        guard let name = try? String(contentsOf: pointer, encoding: .utf8) else { return nil }
        let root = versionsDir.appendingPathComponent(name.trimmingCharacters(in: .whitespacesAndNewlines), isDirectory: true)
        var isDir: ObjCBool = false
        guard fm.fileExists(atPath: root.path, isDirectory: &isDir), isDir.boolValue else { return nil }
        return root
    }

    /// Structural + spot-hash validation of a content root. Full hashing happened
    /// at staging; this catches truncation/corruption without a launch-time cost.
    private func validate(root: URL) -> Bool {
        guard let manifest = try? loadManifest(at: root.appendingPathComponent("ota/manifest.json")) else { return false }
        // The reason this app exists: crisis pages must be present and intact.
        let probes = manifest.files.keys.filter { $0.hasPrefix("/crisis/") && $0.hasSuffix("/index.html") }.sorted().prefix(3)
        guard !probes.isEmpty else { return false }
        for path in probes {
            let f = root.appendingPathComponent(String(path.dropFirst()))
            guard let data = try? Data(contentsOf: f),
                  SHA256.hash(data: data).hexString == manifest.files[path]?.sha256 else { return false }
        }
        return fm.fileExists(atPath: root.appendingPathComponent("index.html").path)
    }

    private func builtAt(inRoot root: URL?) -> Date? {
        guard let root,
              let data = try? Data(contentsOf: root.appendingPathComponent("app-build.json")),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let s = obj["builtAt"] as? String else { return nil }
        return OTAManifest.parseISO8601(s)
    }

    // MARK: - Update check (called after launch, off the main path)

    /// `then` runs on the main queue once the check has settled, so a
    /// user-initiated "check now" can show what actually happened.
    func checkForUpdateInBackground(then completion: (@Sendable () -> Void)? = nil) {
        // A second caller does NOT start a rival run — it attaches to the one in
        // flight and is answered when that finishes. Attaching rather than dropping
        // matters: a "Check now" that silently does nothing is how an update channel
        // stays broken without anyone noticing.
        guard flight.begin(completion: completion) else {
            CAPLog.print("⚡️  OTA: check already in flight — attached to it")
            return
        }
        Task.detached(priority: .utility) { [self] in
            do {
                let outcome = try await checkForUpdate()
                record(outcome, detail: nil)
                CAPLog.print("⚡️  OTA: check finished as \(outcome.rawValue)")
            } catch {
                let (outcome, detail) = OTAOutcome.classify(error)
                record(outcome, detail: detail)
                // Never fatal: the app keeps serving its last-known-good content.
                CAPLog.print("⚡️  OTA: check finished as \(outcome.rawValue) — \(detail)")
            }
            let waiting = flight.finish()
            if !waiting.isEmpty {
                await MainActor.run { for done in waiting { done() } }
            }
        }
    }

    private func record(_ outcome: OTAOutcome, detail: String?) {
        defaults.set(Date(), forKey: Keys.lastCheck)
        defaults.set(outcome.rawValue, forKey: Keys.lastOutcome)
        if let detail { defaults.set(detail, forKey: Keys.lastDetail) }
        else { defaults.removeObject(forKey: Keys.lastDetail) }
    }

    /// Human-readable status for the native content-status sheet.
    func statusSummary(spanish es: Bool) -> String {
        let df = DateFormatter()
        df.dateStyle = .medium
        df.timeStyle = .short
        df.locale = Locale(identifier: es ? "es" : "en_US")

        let otaActive = pointedRoot(currentPointer) != nil
        let servingRoot = otaActive ? pointedRoot(currentPointer) : bundleRoot
        var lines: [String] = []
        if let built = builtAt(inRoot: servingRoot) {
            lines.append((es ? "Contenido del " : "Content from ") + df.string(from: built))
        }
        lines.append(
            otaActive
                ? (es ? "Fuente: actualización descargada y verificada" : "Source: downloaded, signature-verified update")
                : (es ? "Fuente: copia incluida en la app" : "Source: copy shipped with the app")
        )
        // The one thing a reader can act on, so it goes above the diagnostics.
        if updateAwaitingRestart {
            lines.append(es
                ? "Actualización lista: cierra y vuelve a abrir la app para aplicarla."
                : "Update ready — close and reopen the app to apply it.")
        }
        if let last = defaults.object(forKey: Keys.lastCheck) as? Date {
            let when = df.string(from: last)
            // A check recorded by a previous binary has no outcome stored. Say so
            // rather than guessing — inventing a cause is the bug this replaced.
            let outcome = OTAOutcome(rawValue: defaults.string(forKey: Keys.lastOutcome) ?? "")
            let phrase = outcome.map { $0.phrase(spanish: es) }
                ?? (es ? "resultado desconocido" : "outcome not recorded")
            lines.append((es ? "Última comprobación: " : "Last update check: ") + when + " — " + phrase)
            // The technical line. Not pretty, deliberately kept: it is the
            // difference between "it says offline" and a diagnosis.
            if outcome?.isFailure == true, let detail = defaults.string(forKey: Keys.lastDetail), !detail.isEmpty {
                lines.append((es ? "Detalle: " : "Detail: ") + detail)
            }
        } else {
            lines.append(es ? "Aún no se ha comprobado" : "No update check yet")
        }
        if let v = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String {
            lines.append((es ? "Versión de la app: " : "App version: ") + v)
        }
        return lines.joined(separator: "\n")
    }

    private func checkForUpdate() async throws -> OTAOutcome {
        let session = URLSession(configuration: .ephemeral)

        // 1. Fetch manifest + signature; verify BEFORE parsing.
        let manifestBytes = try await fetch(session, baseURL.appendingPathComponent("ota/manifest.json"))
        let sigB64 = String(decoding: try await fetch(session, baseURL.appendingPathComponent("ota/manifest.sig")), as: UTF8.self)
        guard let sig = Data(base64Encoded: sigB64.trimmingCharacters(in: .whitespacesAndNewlines)),
              let pub = Data(base64Encoded: Self.publicKeyB64),
              let key = try? Curve25519.Signing.PublicKey(rawRepresentation: pub),
              key.isValidSignature(sig, for: manifestBytes) else {
            throw OTAError.badSignature
        }
        let manifest = try OTAManifest.decode(manifestBytes)
        // Refuse to fall back to per-path fetches against an older publish side:
        // through the edge those return rewritten html that can never match.
        guard manifest.blobPath != nil else {
            throw OTAError.noBlobStore
        }

        // 2. Already current?
        let activeRoot = activeContentRoot() ?? bundleRoot
        guard let activeRoot else { throw OTAError.noContent }
        let activeManifest = try? loadManifest(at: activeRoot.appendingPathComponent("ota/manifest.json"))
        if let active = activeManifest, active.builtAt == manifest.builtAt { return .upToDate }
        // Never move backwards: refuse a manifest older than what we serve
        // (a stale edge cache must not roll crisis content back).
        if let activeBuilt = activeManifest?.builtAtDate, let newBuilt = manifest.builtAtDate,
           newBuilt <= activeBuilt { return .upToDate }

        // 3. Compute the delta and guard its size.
        var delta: [(path: String, entry: OTAManifest.Entry)] = []
        for (path, entry) in manifest.files where activeManifest?.files[path]?.sha256 != entry.sha256 {
            delta.append((path, entry))
        }
        let deltaBytes = delta.reduce(0) { $0 + $1.entry.size }
        guard deltaBytes <= maxDeltaBytes else { throw OTAError.deltaTooLarge(deltaBytes) }
        CAPLog.print("⚡️  OTA: update \(manifest.builtAt) — \(delta.count) files, \(deltaBytes / 1024) KB")

        // 4. Stage: hard-link unchanged files from the active root, download the rest.
        // Unique per run, and sweep anything a previous run left behind (killed
        // mid-stage by suspension or a crash). Belt and braces alongside the
        // single-flight guard: even a future third entry point cannot now collide
        // with an in-progress stage, because no two runs share a directory name.
        try fm.createDirectory(at: versionsDir, withIntermediateDirectories: true)
        for item in (try? fm.contentsOfDirectory(atPath: versionsDir.path)) ?? []
        where item.hasPrefix("staging") {
            try? fm.removeItem(at: versionsDir.appendingPathComponent(item))
        }
        let staging = versionsDir.appendingPathComponent("staging-\(UUID().uuidString)", isDirectory: true)
        try fm.createDirectory(at: staging, withIntermediateDirectories: true)
        // Content roots are re-downloadable; keeping them out of iCloud backups
        // saves the reader's storage quota. (Applies to the whole content dir.)
        var contentDirURL = contentDir
        var excludeFromBackup = URLResourceValues()
        excludeFromBackup.isExcludedFromBackup = true
        try? contentDirURL.setResourceValues(excludeFromBackup)

        let changed = Set(delta.map(\.path))
        for (path, entry) in manifest.files {
            let dest = staging.appendingPathComponent(String(path.dropFirst()))
            try fm.createDirectory(at: dest.deletingLastPathComponent(), withIntermediateDirectories: true)
            if changed.contains(path) {
                let data = try await fetch(session, try blobURL(manifest, entry.sha256))
                guard SHA256.hash(data: data).hexString == entry.sha256 else {
                    throw OTAError.fileHashMismatch(path)
                }
                try data.write(to: dest)
            } else {
                let src = activeRoot.appendingPathComponent(String(path.dropFirst()))
                do { try fm.linkItem(at: src, to: dest) } catch { try fm.copyItem(at: src, to: dest) }
            }
        }

        // 4b. Every path the manifest promises must be present at the size it
        //     promises. Changed files were already hash-verified inline as they
        //     downloaded, and re-hashing the ~87 MB of hard-linked ones would cost
        //     real seconds of CPU to re-prove something already proven. What this
        //     catches is a root that is MISSING files or truncated — the partial
        //     stage — which the four-file launch validation would wave through.
        //     It runs here, off the launch path, so a reader never waits on it.
        for (path, entry) in manifest.files {
            let staged = staging.appendingPathComponent(String(path.dropFirst()))
            let size = (try? fm.attributesOfItem(atPath: staged.path)[.size]) as? Int
            guard size == entry.size else {
                CAPLog.print("⚡️  OTA: staged root incomplete at \(path) — refusing to activate")
                throw OTAError.stagedRootInvalid
            }
        }

        // 5. Carry the signed manifest into the root, and stamp it so the in-app
        //    freshness banner (and the new-binary check) reflect the OTA date.
        try fm.createDirectory(at: staging.appendingPathComponent("ota"), withIntermediateDirectories: true)
        try manifestBytes.write(to: staging.appendingPathComponent("ota/manifest.json"))
        try Data(sigB64.utf8).write(to: staging.appendingPathComponent("ota/manifest.sig"))
        let stamp = ["gitSha": manifest.gitSha ?? "", "builtAt": manifest.builtAt]
        try JSONSerialization.data(withJSONObject: stamp).write(to: staging.appendingPathComponent("app-build.json"))

        // 6. Activate atomically for the NEXT launch; keep one rollback root.
        let versionName = "v-" + manifest.builtAt.replacingOccurrences(of: ":", with: "-")
        let finalRoot = versionsDir.appendingPathComponent(versionName, isDirectory: true)
        try? fm.removeItem(at: finalRoot)
        try fm.moveItem(at: staging, to: finalRoot)
        guard validate(root: finalRoot) else {
            try? fm.removeItem(at: finalRoot)
            throw OTAError.stagedRootInvalid
        }
        let oldCurrent = try? String(contentsOf: currentPointer, encoding: .utf8)
        try? fm.removeItem(at: previousPointer)
        if let oldCurrent { try oldCurrent.write(to: previousPointer, atomically: true, encoding: .utf8) }
        try versionName.write(to: currentPointer, atomically: true, encoding: .utf8)
        defaults.set(versionName, forKey: Keys.pendingVersion)

        // 7. Prune everything that is neither current nor previous.
        let keep: Set<String> = [versionName, oldCurrent?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""]
        for item in (try? fm.contentsOfDirectory(atPath: versionsDir.path)) ?? [] where !keep.contains(item) {
            try? fm.removeItem(at: versionsDir.appendingPathComponent(item))
        }
        CAPLog.print("⚡️  OTA: staged \(versionName); activates on next launch")
        return .staged
    }

    /// `/ota/blobs` + `ab` + `abcdef…` — the sha256 from the SIGNED manifest is the
    /// whole address, so there is nothing here an attacker could point elsewhere
    /// without breaking the signature. decodeManifest has already checked that the
    /// hash is 64 hex characters, so this can't traverse.
    /// The blob address comes from OTACore, which refuses to build one from a
    /// malformed hash or a manifest with no blob store — so a nil here means
    /// "refuse this update", never "guess a path".
    private func blobURL(_ manifest: OTAManifest, _ sha256: String) throws -> URL {
        guard let rel = manifest.blobRelativePath(forSHA: sha256) else { throw OTAError.badManifest }
        return baseURL.appendingPathComponent(rel)
    }

    private func fetch(_ session: URLSession, _ url: URL) async throws -> Data {
        let (data, response) = try await session.data(from: url)
        guard let http = response as? HTTPURLResponse else { throw OTAError.httpFailure(url.path, 0) }
        guard http.statusCode == 200 else { throw OTAError.httpFailure(url.path, http.statusCode) }
        return data
    }

    private func loadManifest(at url: URL) throws -> OTAManifest {
        try OTAManifest.decode(try Data(contentsOf: url))
    }
}

private extension SHA256.Digest {
    var hexString: String { map { String(format: "%02x", $0) }.joined() }
}
