#!/usr/bin/env python3
"""Check that section index.md pages list the pages that live in their section.

The sidebar is autogenerated, but the hand-written per-section index.md pages
are not -- they drift. This checker diffs each index's links against the pages
actually on disk, for both the English tree (repo root) and the Spanish tree
(es/). It exists because seven pages (some shipped weeks earlier) were found
unlisted on their indexes on 2026-08-18.

Ownership model: a page belongs to the NEAREST ancestor directory that has an
index.md. So community/online-communities/discord.md is owned by
community/online-communities/index.md, not community/index.md -- a top index is
not penalized for delegating to a sub-index.

Not every index is exhaustive by design (foundations/index.md is a curated
hub). Intentional omissions go in scripts/index_parity_allowlist.txt as
one slug per line (e.g. /foundations/epistemic-injustice); the es/ mirror of an
allowlisted slug is allowed automatically. Lines starting with # are comments.

Exit code: 0 in default (advisory) mode; --strict exits 1 if anything is
missing. Run from the repo root.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ALLOWLIST_FILE = ROOT / "scripts" / "index_parity_allowlist.txt"

# Directories that are not reader-facing content sections.
NON_CONTENT = {
    "site", "scripts", "docs", "backups", "app", "node_modules", "es",
    ".git", ".github", ".claude", ".agents", ".codex",
    "page-review-2026-06-05", "_desktop_inbox",
}

LINK_RE = re.compile(r"\]\((/[^)\s#?]+)")


def normalize(slug):
    """Compare case-insensitively (Rights/ dir vs /rights/ URLs) and accept
    legacy Wiki.js-era links that carry a .md suffix or trailing slash."""
    slug = slug.rstrip("/")
    if slug.endswith(".md"):
        slug = slug[:-3]
    return slug.lower()


def load_allowlist():
    allowed = set()
    if ALLOWLIST_FILE.exists():
        for line in ALLOWLIST_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                allowed.add(normalize(line))
    return allowed


def is_draft(md_path):
    try:
        head = md_path.read_text(errors="replace")[:500]
    except OSError:
        return False
    return bool(re.search(r"^draft:\s*true", head, re.MULTILINE)) or bool(
        re.search(r"^published:\s*false", head, re.MULTILINE)
    )


def find_indexes(tree_root):
    """Every index.md under the content tree, skipping non-content dirs."""
    indexes = []
    for idx in tree_root.rglob("index.md"):
        rel = idx.relative_to(tree_root)
        if rel.parts and rel.parts[0] in NON_CONTENT:
            continue
        indexes.append(idx)
    return indexes


def owning_index(page, index_dirs, tree_root):
    """Nearest ancestor directory (within the tree) that has an index.md."""
    for parent in page.parents:
        if parent == tree_root.parent:
            break
        if parent in index_dirs:
            return parent
    return None


def check_tree(tree_root, url_prefix, allowed):
    """Return list of (index_path, missing_slug) for one locale tree."""
    indexes = find_indexes(tree_root)
    index_dirs = {i.parent for i in indexes}
    missing = []

    for idx in indexes:
        section_dir = idx.parent
        if section_dir == tree_root:  # a root-level index.md is not a section
            continue
        listed = {
            normalize(link) for link in LINK_RE.findall(idx.read_text(errors="replace"))
        }
        for page in sorted(section_dir.rglob("*.md")):
            if page.name == "index.md":
                continue
            if owning_index(page, index_dirs, tree_root) != section_dir:
                continue  # delegated to a sub-index
            if is_draft(page):
                continue
            rel = page.relative_to(tree_root)
            slug = normalize(
                url_prefix + "/" + str(rel.with_suffix("")).replace("\\", "/")
            )
            # es/ pages are excused if their English slug is allowlisted
            english_slug = slug[3:] if url_prefix == "/es" else slug
            if slug in allowed or english_slug in allowed:  # allowlist pre-normalized
                continue
            if slug not in listed:
                missing.append((idx.relative_to(ROOT), slug))
    return missing


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--strict", action="store_true", help="exit 1 on any gap")
    args = ap.parse_args()

    allowed = load_allowlist()
    gaps = check_tree(ROOT, "", allowed) + check_tree(ROOT / "es", "/es", allowed)

    if gaps:
        print(f"Index parity: {len(gaps)} page(s) not listed on their section index\n")
        by_index = {}
        for idx, slug in gaps:
            by_index.setdefault(str(idx), []).append(slug)
        for idx in sorted(by_index):
            print(f"  {idx}:")
            for slug in by_index[idx]:
                print(f"    missing {slug}")
        print(
            "\nAdd each page to its index (or, if intentionally unlisted, add its"
            "\nslug to scripts/index_parity_allowlist.txt)."
        )
    else:
        print("Index parity: all section pages are listed on their indexes.")

    if args.strict and gaps:
        sys.exit(1)


if __name__ == "__main__":
    main()
