-- =============================================================================
-- 0001_wiki_contributions.sql — the community-contribution moderation queue.
--
-- Model (docs/contribution-model.md): pseudonymous suggest-edit / propose-page →
-- THIS queue → maintainer moderation → promotion into markdown. The published
-- static site never reads this table; it is a staging surface only.
--
-- Sensitivity: rows are UNMODERATED user submissions keyed to a pseudonymous
-- contributor. They are server-only — never publicly readable. Writes come from
-- the Cloudflare Pages Function using the service_role key (the function is the
-- trust boundary, BAS invariant #1); anon/authenticated get nothing.
--
-- RLS ≠ GRANT (shared lesson): enabling RLS does not grant table privileges, and
-- Supabase's service_role has BYPASSRLS but still needs explicit table grants.
-- So we (a) enable RLS with no anon/authenticated policies, (b) revoke all from
-- anon/authenticated, and (c) grant the service role exactly what it needs.
-- =============================================================================

create table wiki_contributions (
  id             uuid primary key,               -- generated by the function (crypto.randomUUID)
  contributor_id text not null,                  -- Keycloak PAIRWISE sub, or 'provisional:...' pre-auth (BAS invariant #3)
  provisional    boolean not null default false, -- true = provisional/pre-Keycloak write (local/preview only)
  kind           text not null check (kind in ('suggest_edit', 'propose_page')),
  payload        jsonb not null,                 -- the validated ValidSubmission (page/section/body or title/category/body)
  status         text not null default 'queued'
                   check (status in ('queued', 'approved', 'rejected')),
  created_at     timestamptz not null default now()
);

comment on table wiki_contributions is
  'Community-contribution moderation queue. Unmoderated, sensitive, server-only. Not read by the published site.';
comment on column wiki_contributions.contributor_id is
  'Keycloak PAIRWISE subject (per-app, not cross-app correlatable, BAS invariant #3); "provisional:*" before Keycloak.';

-- Moderator queue scan (oldest queued first) and per-contributor lookup
-- (delete/export by pairwise sub, BAS invariant #3).
create index wiki_contributions_status_idx      on wiki_contributions (status, created_at);
create index wiki_contributions_contributor_idx on wiki_contributions (contributor_id);

-- Server-only: RLS on, zero public policies.
alter table wiki_contributions enable row level security;

-- Belt-and-braces: strip any default privileges from the public roles.
revoke all on wiki_contributions from anon, authenticated;

-- The trusted server role writes and moderates (RLS ≠ GRANT — grant explicitly).
grant select, insert, update on wiki_contributions to service_role;
